### PR TITLE
add: Reframe protocol when using the js-ipfs library

### PR DESCRIPTION
**Pull request by swarna1101**
This PR enables the use of the Reframe protocol when interacting with the IPFS node using js-ipfs. The Reframe protocol is a delegated routing protocol that aims to improve the performance of fetching content from the IPFS network. 

To enable the Reframe protocol, the `reframe` option was added to the `options` object when creating the `jsIpfs` provider. This allows us to take advantage of the improved performance provided by the Reframe protocol when fetching content from the IPFS node.

### CODE REVIEW

**Comment by codynhat** [comment]
Thanks for the PR @swarna1101.

I am not sure exactly what this option does. Can you link to any documentation or code from `js-ipfs` that explains what this option is?

**Comment by swarna1101** [comment]
> Thanks for the PR @swarna1101.
> 
> I am not sure exactly what this option does. Can you link to any documentation or code from `js-ipfs` that explains what this option is?

https://github.com/ipfs/js-ipfs#reframe

**Comment by codynhat** [comment]
That link just goes to the repo and nothing specific about Reframe. Do you have a more specific link?

**Comment by swarna1101** [comment]
> I am not sure exactly what this option does. Can you link to any documentation or code from `js-ipfs` that explains what this option is?

The `reframe` option is an experimental feature in the js-ipfs library that enables the use of the Reframe protocol when interacting with an IPFS node. The Reframe protocol is a delegated routing protocol that aims to improve the performance of fetching content from the IPFS network.

You can find more information about the Reframe protocol in the following documentation:

- The IPFS documentation on Reframe: https://docs.ipfs.io/guides/concepts/reframe/
- The IPFS documentation on the js-ipfs library: https://docs.ipfs.io/reference/api/js-ipfs/

You can also find the source code for the js-ipfs library on GitHub: https://github.com/ipfs/js-ipfs

The `reframe` option is currently implemented in the `IPFS` class in the `src/core/index.js` file in the js-ipfs repository. You can see the implementation of the `reframe` option and how it is used in the code by looking at this file.

**Pull request closed without merging**
