### PR TITLE
Ceramic mainnet + multiquery

### PR DESCRIPTION
**Pull request by codynhat**
- Use Ceramic public mainnet gateway
- Point demo to hardcoded root stream ID (still uses mock location and parcel info)
- Uses a multi query to query for all items in the media gallery

### CODE REVIEW

**Comment by 10dimensions** [comment]
Works out of the box!

Do you think there's scope for querying based on known hierarchy of data ?
https://developers.ceramic.network/build/queries/#query-document-paths

**Review by 10dimensions — APPROVED** [review]

**Comment by codynhat** [comment]
> Works out of the box!
> 
> Do you think there's scope for querying based on known hierarchy of data ?
> https://developers.ceramic.network/build/queries/#query-document-paths

Which multi query are you thinking exactly? Right now, it does a multi query on `mediaGallery` to get all items. Are you saying we could do a single multi query that includes the media gallery and the root parcel content?

**Comment by 10dimensions** [comment]
Yea... A single query which can pick up the subsequent StreamIDs from the response directly.

**Comment by codynhat** [comment]
Can a multi query be used with an array? If so, I think the problem that remains is not knowing the length of the array without first querying `mediaGallery`.

**Comment by 10dimensions** [comment]
Yea... I forgot that!
Made some minor parsers to simplify query script. Merging now

**Pull request merged**
